[package]
name = "fide"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.1"
failure = "0.1.5"
log = "0.4.6"
shell = { git = "https://github.com/shelbyd/rust-shell", rev = "341478729a14a95c11df2e7db836fff58f5ab55e" }
